app: nginx
service: true
horizontalScaler:
  minReplicas: 1
  maxReplicas: 3
  cpuTarget: 50
  memoryTarget: 50

container:
  image: nginx
  version: latest
  pullPolicy: Always
  cpuRequest: 0.2
  memRequest: 0.5Gi
  cpuLimit: 1
  memLimit: 2Gi
  port:
    - name: app
      path: /
      port: 80
  probe:
    livenessProbe:
      httpGet:
        path: /
        port: app
        scheme: HTTP
      initialDelaySeconds: 5
      timeoutSeconds: 5
#configmap:
#  - name: nginx-configmap
#    key:
#      "key": "value"
#secret:
#  - name: nginx-secret
#    key:
#      "key": "dmFsdWUK" # echo -n "value" |base64
