{{- if .Values.serviceAccountRoleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ tpl .Values.serviceAccountRoleArn .}}
{{- end }}
